version: '3.8'

services:

  mysql:
    image: mysql:5.7
    command: mysqld --sql-mode="NO_ENGINE_SUBSTITUTION"
    ports:
      - "3311:3306"
    networks:
      - lipr
    volumes:
      - ./docker/mysql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: db_lr
      MYSQL_USER: developer
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password

  php-fpm:
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
      args:
        environment: dev
        COMPOSER_AUTH: "${COMPOSER_AUTH}"
    depends_on:
      - mysql
    volumes:
      - ./:/usr/src/app
      - "~/.ssh:/root/.ssh"
      - "~/.composer.sh:/root/.composer.sh"
    networks:
      - lipr

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        environment: local
    volumes:
      - ./:/usr/src/app
    ports:
      - "14777:80"
    networks:
      - lipr
    depends_on:
      - php-fpm

networks:
  lipr:
    external: true